version: '2.5.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    container_name: app
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: postgres
    ports:
      - '5433:5432' #  CONTAINER_PORT: 5432 HOST_PORT: 5433
    container_name: db
